export const maritalStatus = [
  "Single",
  "Married",
  "Unmarried",
  "Widow",
  "Divorce",
];

export const nationalies = [
  "Afghan",
  "Albanian",
  "Algerian",
  "Andorran",
  "Angolan",
  "Antiguan and Barbudan",
  "Argentine",
  "Armenian",
  "Australian",
  "Austrian",
  "Azerbaijani",
  "Bahamian",
  "Bahraini",
  "Bangladeshi",
  "Barbadian",
  "Belarusian",
  "Belgian",
  "Belizean",
  "Beninese",
  "Bhutanese",
  "Bolivian",
  "Bosnian and Herzegovinian",
  "Botswanan",
  "Brazilian",
  "Bruneian",
  "Bulgarian",
  "Burkinabé",
  "Burundian",
  "Cabo Verdean",
  "Cambodian",
  "Cameroonian",
  "Canadian",
  "Central African",
  "Chadian",
  "Chilean",
  "Chinese",
  "Colombian",
  "Comorian",
  "Congolese (Brazzaville)",
  "Congolese (Kinshasa)",
  "Costa Rican",
  "Croatian",
  "Cuban",
  "Cypriot",
  "Czech",
  "Danish",
  "Djiboutian",
  "Dominican",
  "Ecuadorian",
  "Egyptian",
  "Salvadoran",
  "Equatorial Guinean",
  "Eritrean",
  "Estonian",
  "Eswatini",
  "Ethiopian",
  "Fijian",
  "Finnish",
  "French",
  "Gabonese",
  "Gambian",
  "Georgian",
  "German",
  "Ghanaian",
  "Greek",
  "Grenadian",
  "Guatemalan",
  "Guinean",
  "Bissau-Guinean",
  "Guyanese",
  "Haitian",
  "Honduran",
  "Hungarian",
  "Icelander",
  "Indian",
  "Indonesian",
  "Iranian",
  "Iraqi",
  "Irish",
  "Israeli",
  "Italian",
  "Jamaican",
  "Japanese",
  "Jordanian",
  "Kazakh",
  "Kenyan",
  "Kiribati",
  "Kuwaiti",
  "Kyrgyz",
  "Lao",
  "Latvian",
  "Lebanese",
  "Basotho",
  "Liberian",
  "Libyan",
  "Liechtensteiner",
  "Lithuanian",
  "Luxembourgish",
  "Malagasy",
  "Malawian",
  "Malaysian",
  "Maldivian",
  "Malian",
  "Maltese",
  "Mauritanian",
  "Mauritian",
  "Mexican",
  "Moldovan",
  "Monacan",
  "Mongolian",
  "Montenegrin",
  "Moroccan",
  "Mozambican",
  "Burmese",
  "Namibian",
  "Nauruan",
  "Nepali",
  "Dutch",
  "New Zealander",
  "Nicaraguan",
  "Nigerien",
  "Nigerian",
  "North Korean",
  "Macedonian",
  "Norwegian",
  "Omani",
  "Pakistani",
  "Palauan",
  "Panamanian",
  "Papua New Guinean",
  "Paraguayan",
  "Peruvian",
  "Filipino",
  "Polish",
  "Portuguese",
  "Qatari",
  "Romanian",
  "Russian",
  "Rwandan",
  "Saudi",
  "Senegalese",
  "Serbian",
  "Singaporean",
  "Slovak",
  "Slovenian",
  "South African",
  "South Korean",
  "Spanish",
  "Sri Lankan",
  "Sudanese",
  "Swedish",
  "Swiss",
  "Turkish",
  "Ukrainian",
  "Emirati",
  "British",
  "American",
  "Vietnamese",
  "Yemeni",
  "Zambian",
  "Zimbabwean",
];

export const employmentTypes = [
  "Full Time",
  "Part Time",
  "Contractual",
  "Suspend",
  "Left",
];

export const kinRelationships = [
  "Father",
  "Mother",
  "Brother",
  "Sister",
  "Spouse",
  "Son",
  "Daughter",
  "Uncle",
  "Aunt",
  "Cousin",
  "Grandfather",
  "Grandmother",
  "Friend",
  "Partner",
  "Guardian",
  "Other",
];

export const payGroups = ["Group 1", "Group 2"];

export const wadgesPayModes = ["Pay 1", "Pay 2"];

export const annualPays = ["Annual Pay 1", "Annual Pay 2"];

export const payTypes = [
  "Annualy",
  "Monthly",
  "Weekly",
  "Bi-Weekly",
  "Daily",
  "Hourly",
  "Commission",
];

export const taxCodes = ["Tax Code 1", "Tax Code 2"];

export const payModes = ["Mode 1", "Mode 2"];

export const bankNames = [
  "Chase Bank (USA)",
  "Bank of America (USA)",
  "Wells Fargo (USA)",
  "Citibank (Global)",
  "HSBC (UK & Global)",
  "Barclays (UK)",
  "Deutsche Bank (Germany)",
  "Standard Chartered (Global)",
];

export const paymentCurrencies = [
  "USD - United States Dollar",
  "EUR - Euro (European Union)",
  "GBP - British Pound Sterling (UK)",
  "INR - Indian Rupee (India)",
  "JPY - Japanese Yen (Japan)",
  "CAD - Canadian Dollar (Canada)",
  "AUD - Australian Dollar (Australia)",
  "CNY - Chinese Yuan (China)",
];

// employee file fields
export const employeeFileFields = [
  "profilePicture",
  "proofOfAddress",
  "passportDocument",
  "visaDocumentFrontSide",
  "visaDocumentBackSide",
  "eussDocument",
  "dbsDocument",
  "nationalIdDocument",
  "othersUploadDocument",
];
